main: main.cpp Interface.o Resource.o Spider.o Time.o Date.o
	g++ main.cpp Interface.o Resource.o Spider.o Time.o Date.o -o main

Date.o: Date.cpp Date.h
	g++ -c Date.cpp -o Date.o

Interface.o: Interface.cpp Interface.h
	g++ -c Interface.cpp -o Interface.o

Resource.o: Resource.cpp Resource.h
	g++ -c Resource.cpp -o Resource.o

Spider.o: Spider.cpp Spider.h
	g++ -c Spider.cpp -o Spider.o

Time.o: Time.cpp Time.h
	g++ -c Time.cpp -o Time.o


Date.o: Date.cpp Date.h
	g++ -c Date.cpp -o Date.o
